module: src.client.agents.HTTPAgent
parameters:
  name: <% NAME %>
  url: https://api.shubiaobiao.cn/v1/chat/completions
  headers:
    Content-Type: application/json
    Authorization: Bearer sk-zbXhyvwxAkF9bkPEC9Cc8218Fe3a4b86BbFdD21e77340aAa
  body:
    model: <% NAME %>
    temperature: 0
  prompter:
    name: prompt_string
  return_format: "{response[choices][0][text]}"

