module: src.client.agents.HTTPAgent
parameters:
  url: https://api.shubiaobiao.cn/v1/chat/completions
  headers:
    Content-Type: application/json
    Authorization: Bearer sk-zbXhyvwxAkF9bkPEC9Cc8218Fe3a4b86BbFdD21e77340aAa
  body:
    temperature: 0
  prompter:
    name: role_content_dict
    args:
      agent_role: assistant
  return_format: "{response[choices][0][message][content]}"
